version: '3'
services:
  # app:
  #   container_name: app
  #   restart: always
  #   build:
  #     context: ..
  #     dockerfile: ./release/Dockerfile
  #   ports:
  #     - "9000:9000"
  #   links:
  #     - mongo
  #   tty: true
  #   stdin_open: true

  mongo:
    restart: always
    container_name: mongo
    image: mongo:3.4.18
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/mongo_log
      - MONGODB_USER="appdev"
      - MONGODB_PASS="dev123"
      - MONGO_DATABASE='users'
    volumes:
      - ../data:/data/db
      - ../log/mongo_log:/dev/mongo_log
    ports:
      - "27017:27017"
    tty: true
    stdin_open: true
